# Generated by Django 5.2.12 on 2026-03-31 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('strategy_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('symbols', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=20)),
                ('final_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('total_return_pct', models.FloatField(null=True)),
                ('max_drawdown_pct', models.FloatField(null=True)),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('win_rate', models.FloatField(null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('avg_win_pct', models.FloatField(null=True)),
                ('avg_loss_pct', models.FloatField(null=True)),
                ('profit_factor', models.FloatField(null=True)),
                ('equity_curve', models.JSONField(default=list)),
                ('trades_log', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
