# Generated by Django 5.2.13 on 2026-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0002_backtest_run_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backtestrunv2',
            new_name='backtester__config__8c9e05_idx',
            old_name='bt_v2_hash_created_idx',
        ),
        migrations.AlterField(
            model_name='backtestrunv2',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
