# Generated by Django 5.2.17 on 2026-10-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backtester",
            "0003_rename_bt_v2_hash_created_idx_backtester__config__8c9e05_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvingVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(db_index=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("family", models.CharField(db_index=True, max_length=40)),
                (
                    "live_rule",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("params", models.JSONField(default=dict)),
                ("direction", models.CharField(max_length=5)),
                ("filter", models.CharField(default="none", max_length=12)),
                ("asset_class", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(default="4h", max_length=4)),
                ("generated", models.BooleanField(default=False)),
                ("n_candidates", models.IntegerField(default=1)),
                ("symbols_n", models.IntegerField(default=0)),
                ("trades_n", models.IntegerField(default=0)),
                ("holdout_n", models.IntegerField(default=0)),
                ("expectancy", models.FloatField(null=True)),
                ("holdout_expectancy", models.FloatField(null=True)),
                ("lower_bound", models.FloatField(null=True)),
                ("stressed_expectancy", models.FloatField(null=True)),
                ("win_rate", models.FloatField(null=True)),
                ("payoff", models.FloatField(null=True)),
                ("max_dd_r", models.FloatField(null=True)),
                ("positive_folds", models.IntegerField(default=0)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("proven", "Proven"),
                            ("promising", "Promising"),
                            ("failed", "Failed"),
                            ("insufficient", "Insufficient"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("why", models.TextField(blank=True)),
                ("detail", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-lower_bound"],
                "indexes": [
                    models.Index(
                        fields=["live_rule", "asset_class", "-created_at"],
                        name="backtester__live_ru_8c29f3_idx",
                    )
                ],
            },
        ),
    ]
