# Generated by Django 5.2.17 on 2026-10-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0004_proving_verdict"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProvingTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=40)),
                ("entry_ts", models.DateTimeField()),
                ("exit_ts", models.DateTimeField()),
                ("r", models.FloatField()),
                ("mfe", models.FloatField(default=0.0)),
                ("regime", models.CharField(default="", max_length=16)),
                ("reason", models.CharField(default="", max_length=24)),
                ("bars", models.IntegerField(default=0)),
                (
                    "verdict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="backtester.provingverdict",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["verdict", "-entry_ts"],
                        name="backtester__verdict_c1deb3_idx",
                    ),
                    models.Index(
                        fields=["verdict", "regime", "-entry_ts"],
                        name="backtester__verdict_be763f_idx",
                    ),
                ],
            },
        ),
    ]
