# Generated by Django 5.2.17 on 2026-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtester", "0005_proving_trade"),
    ]

    operations = [
        migrations.AddField(
            model_name="provingtrade",
            name="mae",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name="provingtrade",
            index=models.Index(
                fields=["verdict", "mae"], name="backtester__verdict_1bf34b_idx"
            ),
        ),
    ]
