# Generated by Django 4.2.29 on 2026-04-08 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sauron Bot', max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('paper', 'Paper Trading (simulated, safe)'), ('live', 'Live Trading (real funds)')], default='paper', max_length=8)),
                ('symbols', models.JSONField(default=list, help_text='Symbols, e.g. ["BTCUSDT","ETHUSDT"]')),
                ('base_quote', models.CharField(default='USDT', max_length=8)),
                ('capital_usdt', models.DecimalField(decimal_places=2, default=1000, max_digits=14)),
                ('position_size_pct', models.FloatField(default=5.0, help_text='% of capital per trade')),
                ('max_concurrent_positions', models.IntegerField(default=4)),
                ('max_daily_loss_pct', models.FloatField(default=3.0)),
                ('stop_loss_pct', models.FloatField(default=1.5)),
                ('take_profit_pct', models.FloatField(default=3.0)),
                ('trailing_stop_pct', models.FloatField(default=1.0)),
                ('leverage', models.FloatField(default=1.0, help_text='Futures only; 1 = spot')),
                ('w_technical', models.FloatField(default=0.3)),
                ('w_sauron_sig', models.FloatField(default=0.25)),
                ('w_news', models.FloatField(default=0.15)),
                ('w_liquidity', models.FloatField(default=0.15)),
                ('w_macro', models.FloatField(default=0.1)),
                ('w_sentiment', models.FloatField(default=0.05)),
                ('entry_score_min', models.FloatField(default=0.6, help_text='0–1; min composite score to open')),
                ('exit_score_max', models.FloatField(default=0.35, help_text='Close if score drops below this')),
                ('tick_interval_sec', models.IntegerField(default=60)),
                ('timeframe', models.CharField(default='15m', max_length=6)),
                ('cool_down_minutes', models.IntegerField(default=20)),
                ('halt_on_high_impact_news', models.BooleanField(default=True)),
                ('halt_on_drawdown', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='OPEN', max_length=10)),
                ('pnl_usdt', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('composite_score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('paper', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('binance_order_id', models.CharField(blank=True, max_length=64)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bot_program.botconfig')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BotScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('symbols', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('params', models.JSONField(default=dict, help_text='Overrides for BotConfig fields')),
                ('final_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_return_pct', models.FloatField(blank=True, null=True)),
                ('max_drawdown_pct', models.FloatField(blank=True, null=True)),
                ('sharpe', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('num_trades', models.IntegerField(default=0)),
                ('equity_curve', models.JSONField(default=list)),
                ('trades_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Main', max_length=60)),
                ('api_key_enc', models.TextField(blank=True)),
                ('api_secret_enc', models.TextField(blank=True)),
                ('testnet', models.BooleanField(default=True, help_text='Use Binance Testnet (recommended)')),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_balance_usdt', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binance_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
