# Generated by Django 5.0.6 on 2026-04-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0004_alter_botcircuitstate_id_alter_botheartbeat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlpacaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Main', max_length=60)),
                ('api_key_enc', models.TextField(blank=True)),
                ('api_secret_enc', models.TextField(blank=True)),
                ('paper', models.BooleanField(default=True, help_text='Use Alpaca paper endpoint.')),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_balance_usd', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alpaca_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OANDAAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Main', max_length=60)),
                ('api_key_enc', models.TextField(blank=True)),
                ('account_id_enc', models.TextField(blank=True)),
                ('practice', models.BooleanField(default=True, help_text='Use OANDA practice (demo) endpoint.')),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_balance', models.DecimalField(decimal_places=4, default=0, help_text='In account base currency.', max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oanda_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
