# Generated by Django 5.0.6 on 2026-05-01 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0005_alpacaaccount_oandaaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('stock', 'Stocks'), ('forex', 'Forex'), ('commodity', 'Commodities')], db_index=True, max_length=12)),
                ('name', models.CharField(default='Asset Bot', max_length=80)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('paper', 'Paper Trading (simulated, safe)'), ('live', 'Live Trading (real funds)')], default='paper', max_length=8)),
                ('symbols', models.JSONField(default=list, help_text='Symbols, e.g. ["AAPL","MSFT"] for stocks.')),
                ('capital', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),
                ('base_currency', models.CharField(default='USD', max_length=10)),
                ('position_size_pct', models.FloatField(default=2.0, help_text='% of capital per new position.')),
                ('max_concurrent_positions', models.IntegerField(default=5)),
                ('max_daily_loss_pct', models.FloatField(default=2.0)),
                ('stop_loss_pct', models.FloatField(default=1.5)),
                ('take_profit_pct', models.FloatField(default=3.0)),
                ('entry_score_min', models.FloatField(default=0.6)),
                ('exit_score_max', models.FloatField(default=0.35)),
                ('min_signals_for_entry', models.IntegerField(default=1, help_text='Minimum number of active Signals confirming the same direction to enter.')),
                ('timeframe', models.CharField(default='1h', max_length=8)),
                ('cool_down_minutes', models.IntegerField(default=60)),
                ('halt_on_drawdown', models.BooleanField(default=True)),
                ('halt_on_high_impact_news', models.BooleanField(default=False)),
                ('extras', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_bot_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetBotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(db_index=True, max_length=12)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='OPEN', max_length=10)),
                ('pnl', models.DecimalField(decimal_places=4, default=0, help_text="Realized P&L in the config's base_currency.", max_digits=14)),
                ('composite_score', models.FloatField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('rule_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paper', models.BooleanField(default=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='bot_program.assetbotconfig')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetbotconfig',
            index=models.Index(fields=['enabled', 'asset_class'], name='bot_program_enabled_7fe9b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetbotconfig',
            unique_together={('user', 'asset_class', 'name')},
        ),
        migrations.AddIndex(
            model_name='assetbottrade',
            index=models.Index(fields=['config', 'status'], name='bot_program_config__4b2d66_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbottrade',
            index=models.Index(fields=['asset_class', '-opened_at'], name='bot_program_asset_c_49750c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbottrade',
            index=models.Index(fields=['rule_name', '-opened_at'], name='bot_program_rule_na_38fac6_idx'),
        ),
    ]
