# Generated by Django 5.0.6 on 2026-05-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0006_assetbotconfig_assetbottrade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IBKRAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Main', max_length=60)),
                ('host', models.CharField(default='127.0.0.1', max_length=120)),
                ('port', models.IntegerField(default=7497, help_text='7497=TWS paper, 7496=TWS live, 4002=Gateway paper, 4001=Gateway live.')),
                ('client_id', models.IntegerField(default=1, help_text='API client ID. Allows multiple connections to the same TWS.')),
                ('account_id_enc', models.TextField(blank=True)),
                ('paper', models.BooleanField(default=True, help_text='Informational — actual paper/live behaviour follows TWS port.')),
                ('is_primary_for_stocks', models.BooleanField(default=False)),
                ('is_primary_for_forex', models.BooleanField(default=False)),
                ('is_primary_for_options', models.BooleanField(default=True, help_text="IBKR is the default for options since Alpaca/OANDA don't trade them at scale.")),
                ('is_primary_for_commodity', models.BooleanField(default=False, help_text='IBKR routes futures via FUT contracts; commodity bot still defers to PaperTrader unless this is on.')),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_balance_usd', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ibkr_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
