# Generated by Django 5.0.6 on 2026-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0007_ibkraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbotconfig',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stocks'), ('forex', 'Forex'), ('commodity', 'Commodities'), ('options', 'Options')], db_index=True, max_length=12),
        ),
    ]
