# Generated by Django 5.0.6 on 2026-05-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0008_alter_assetbotconfig_asset_class'),
        ('instruments', '0002_alter_instrument_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, db_index=True, max_length=64)),
                ('strike', models.DecimalField(decimal_places=4, max_digits=14)),
                ('expiry', models.DateField(db_index=True)),
                ('right', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('multiplier', models.IntegerField(default=100)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('bid', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('iv', models.FloatField(blank=True, help_text='Implied volatility, decimal (0.30 = 30%).', null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('gamma', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('vega', models.FloatField(blank=True, null=True)),
                ('open_interest', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('underlying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_contracts', to='instruments.instrument')),
            ],
            options={
                'ordering': ['underlying', 'expiry', 'strike', 'right'],
                'indexes': [models.Index(fields=['underlying', 'expiry'], name='bot_program_underly_d73d73_idx'), models.Index(fields=['expiry', 'right'], name='bot_program_expiry_2e39c9_idx')],
                'unique_together': {('underlying', 'strike', 'expiry', 'right')},
            },
        ),
    ]
