# Generated by Django 5.0.6 on 2026-05-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0009_optioncontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibkraccount',
            name='is_primary_for_cfd',
            field=models.BooleanField(default=False, help_text='IBKR CFD trading — indices, commodities, shares. NOT available to US residents (IBKR LLC blocks CFDs); UK/EU/SG/HK accounts only.'),
        ),
        migrations.AlterField(
            model_name='assetbotconfig',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stocks'), ('forex', 'Forex'), ('commodity', 'Commodities'), ('options', 'Options'), ('cfd', 'CFDs')], db_index=True, max_length=12),
        ),
    ]
