# Generated by Django 5.0.6 on 2026-05-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0010_ibkraccount_is_primary_for_cfd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(db_index=True, max_length=12)),
                ('symbol', models.CharField(max_length=40)),
                ('side', models.CharField(max_length=4)),
                ('right', models.CharField(blank=True, help_text='C / P for options, blank otherwise.', max_length=1)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('reject', 'Reject')], db_index=True, max_length=8)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('exposure_before', models.JSONField(blank=True, default=dict)),
                ('exposure_after', models.JSONField(blank=True, default=dict)),
                ('caps', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestrator_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bot_program_user_id_df3ffa_idx'), models.Index(fields=['decision', '-created_at'], name='bot_program_decisio_006fc5_idx')],
            },
        ),
    ]
