# Generated by Django 5.0.6 on 2026-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0011_orchestratorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbottrade',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetbottrade',
            name='outcome',
            field=models.CharField(blank=True, choices=[('hit_target', 'Hit Target'), ('stopped_out', 'Stopped Out'), ('manual_close', 'Manually Closed'), ('expired', 'Expired')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetbottrade',
            name='realized_r',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
