# Generated by Django 5.0.6 on 2026-05-02 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0013_botbacktestrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTrackRecordAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100)),
                ('asset_class', models.CharField(db_index=True, max_length=12)),
                ('recent_n', models.IntegerField(default=0)),
                ('recent_avg_r', models.FloatField(default=0)),
                ('recent_win_rate', models.FloatField(default=0)),
                ('baseline_n', models.IntegerField(default=0)),
                ('baseline_avg_r', models.FloatField(default=0)),
                ('baseline_win_rate', models.FloatField(default=0)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alerted_at', models.DateTimeField(blank=True, help_text='When the notification dispatch fired (None on dispatch failure).', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When subsequent checks showed the rule had recovered.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_record_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'rule_name', 'asset_class', '-detected_at'], name='bot_program_user_id_b70611_idx'), models.Index(fields=['resolved_at'], name='bot_program_resolve_233fed_idx')],
            },
        ),
    ]
