# Generated by Django 5.0.6 on 2026-05-02 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0014_ruletrackrecordalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('trade_open', 'Trade Opened'), ('trade_close', 'Trade Closed'), ('gate_reject', 'Orchestrator Reject'), ('rule_action', 'Rule Control Action'), ('promotion', 'Stage Promotion'), ('admin_action', 'Admin Action'), ('system', 'System Event')], db_index=True, max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bot_program_user_id_5af986_idx')],
            },
        ),
    ]
