# Generated by Django 5.0.6 on 2026-05-02 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0015_auditlogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(db_index=True, max_length=12)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('qty_initial', models.DecimalField(decimal_places=8, max_digits=18)),
                ('qty_remaining', models.DecimalField(decimal_places=8, max_digits=18)),
                ('cost_basis_per_unit', models.DecimalField(decimal_places=8, max_digits=18)),
                ('multiplier', models.IntegerField(default=1, help_text='Contract multiplier for options/futures (100 for equity options).')),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set when qty_remaining reaches 0.', null=True)),
                ('method_at_open', models.CharField(choices=[('FIFO', 'First In, First Out'), ('LIFO', 'Last In, First Out'), ('HIFO', 'Highest Cost In, First Out')], default='FIFO', max_length=4)),
                ('paper', models.BooleanField(db_index=True, default=True, help_text='Paper trades tracked for parity; tax export filters by mode.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_tax_lots', to='bot_program.assetbottrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxLotConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_consumed', models.DecimalField(decimal_places=8, max_digits=18)),
                ('sale_price_per_unit', models.DecimalField(decimal_places=8, max_digits=18)),
                ('sold_at', models.DateTimeField(db_index=True)),
                ('realized_gain', models.DecimalField(decimal_places=4, help_text='(sale - cost) × qty × multiplier. Signed.', max_digits=18)),
                ('holding_period_days', models.IntegerField(default=0)),
                ('long_term', models.BooleanField(db_index=True, default=False, help_text='True iff holding_period_days >= 365 (US LT capital gains threshold).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consuming_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_consumptions', to='bot_program.assetbottrade')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='bot_program.taxlot')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taxlot',
            index=models.Index(fields=['user', 'symbol', 'asset_class', 'qty_remaining'], name='bot_program_user_id_7af63a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxlot',
            index=models.Index(fields=['user', '-opened_at'], name='bot_program_user_id_11c04b_idx'),
        ),
        migrations.AddIndex(
            model_name='taxlotconsumption',
            index=models.Index(fields=['lot', '-sold_at'], name='bot_program_lot_id_9eb1ce_idx'),
        ),
    ]
