# Generated by Django 5.2.12 on 2026-08-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0016_taxlot_taxlotconsumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbottrade',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE_PENDING', 'Close pending'), ('CLOSED', 'Closed'), ('CANCELED', 'Canceled'), ('ERROR', 'Error')], default='OPEN', max_length=16),
        ),
    ]
