# Generated by Django 5.0.6 on 2026-08-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0017_alter_assetbottrade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbotconfig',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stocks'), ('forex', 'Forex'), ('commodity', 'Commodities'), ('options', 'Options'), ('crypto', 'Crypto'), ('cfd', 'CFDs')], db_index=True, max_length=12),
        ),
    ]
