# Generated by Django 5.2.12 on 2026-08-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0018_add_crypto_asset_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botconfig',
            options={'ordering': ['user__username']},
        ),
    ]
