# Generated by Django 5.2.12 on 2026-08-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0020_assetbotconfig_max_hold_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibkraccount',
            name='client_id',
            field=models.IntegerField(default=1, help_text='BASE API client ID — must be UNIQUE per account and below 100. Sauron opens several sockets at once (trading, data feed, connection test) and derives a distinct id for each from this number; IBKR evicts the earlier holder when two connections share one.'),
        ),
    ]
