# Generated by Django 5.2.12 on 2026-08-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0021_alter_ibkraccount_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibkraccount',
            name='gateway_slot',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which ibgateway container serves this login (1-5). Logins that differ need different slots; accounts under the SAME login should share one.'),
        ),
        migrations.AddField(
            model_name='ibkraccount',
            name='password_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ibkraccount',
            name='username_enc',
            field=models.TextField(blank=True),
        ),
    ]
