# Generated by Django 5.2.12 on 2026-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0022_ibkraccount_gateway_slot_ibkraccount_password_enc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbottrade',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text="Realized P&L in the config's base_currency. NULL means the exit could not be priced — unmeasured, not zero.", max_digits=14, null=True),
        ),
    ]
