# Generated by Django 5.2.12 on 2026-08-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0023_pnl_can_be_unmeasured'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibkraccount',
            name='broker_positions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibkraccount',
            name='broker_positions_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibkraccount',
            name='last_equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ibkraccount',
            name='last_equity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ibkraccount',
            name='last_equity_currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
