# Generated by Django 5.2.17 on 2026-09-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0024_the_brokers_own_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibkraccount',
            name='client_id',
            field=models.IntegerField(default=1, help_text='BASE API client ID — must be UNIQUE per account and below 100. Sauron opens several sockets at once (trading, data feed, connection test) and derives a distinct id for each from this number. When two connections ask for the SAME id, IBKR REFUSES the second (error 326) — it does not evict the first. So a collision looks like a broker that will not answer, never like a session that was stolen, and the trading id is held exclusively for that reason.'),
        ),
        migrations.AlterField(
            model_name='ibkraccount',
            name='port',
            field=models.IntegerField(default=7497, help_text='7497=TWS paper, 7496=TWS live, 4002=Gateway paper, 4001=Gateway live. DOCKERISED Gateway (the deploy stack): 4004=paper, 4003=live - the image relays through socat and refuses 4001/4002 from other containers.'),
        ),
    ]
