# Generated by Django 5.2.17 on 2026-09-11 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0025_alter_ibkraccount_client_id_alter_ibkraccount_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerEquityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(blank=True, default='', max_length=8)),
                ('env', models.CharField(blank=True, default='', max_length=5)),
                ('at', models.DateTimeField(db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_readings', to='bot_program.ibkraccount')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['account', '-at'], name='bot_program_account_0153f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'at'), name='one_reading_per_sync')],
            },
        ),
        migrations.CreateModel(
            name='SharePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('proposed', 'Proposed (shadow)'), ('applied', 'Applied'), ('rejected', 'Rejected by admin'), ('rolled_back', 'Rolled back'), ('expired', 'Expired')], db_index=True, default='proposed', max_length=16)),
                ('reading_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reading_currency', models.CharField(blank=True, default='', max_length=8)),
                ('reading_at', models.DateTimeField(blank=True, null=True)),
                ('reading_age_s', models.IntegerField(blank=True, null=True)),
                ('hwm', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('drawdown_pct', models.FloatField(blank=True, null=True)),
                ('governor', models.FloatField(default=1.0)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('current_shares', models.JSONField(blank=True, default=dict)),
                ('previous_shares', models.JSONField(blank=True, default=dict)),
                ('configs_considered', models.IntegerField(default=0)),
                ('configs_skipped', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('grade_score', models.FloatField(blank=True, null=True)),
                ('grade_detail', models.JSONField(blank=True, default=dict)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_plans_confirmed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['state', '-proposed_at'], name='bot_program_state_77e649_idx')],
            },
        ),
    ]
