# Generated by Django 5.2.17 on 2026-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0026_share_allocator'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareplan',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('shock', 'Shock (de-risk only)'), ('expansion', 'Expansion')], db_index=True, default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='shareplan',
            name='mode_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
