# Generated by Django 5.2.17 on 2026-09-12 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0027_share_plan_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('venue', models.CharField(choices=[('paper', 'Paper'), ('live', 'Live')], max_length=5)),
                ('mode', models.CharField(choices=[('shadow', 'Shadow (recorded, the fleet is unchanged)'), ('live', 'Live (the fleet obeys the plan)')], default='shadow', max_length=6)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('book_risk', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('new_risk_chosen', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('n_candidates', models.IntegerField(default=0)),
                ('n_chosen', models.IntegerField(default=0)),
                ('n_displaced', models.IntegerField(default=0)),
                ('n_resized', models.IntegerField(default=0)),
                ('n_duplicate', models.IntegerField(default=0)),
                ('n_not_desked', models.IntegerField(default=0)),
                ('matrix_pairs_measured', models.IntegerField(default=0)),
                ('matrix_pairs_total', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('edge_r', models.FloatField(blank=True, null=True)),
                ('edge_detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeskDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=40)),
                ('direction', models.CharField(max_length=4)),
                ('rule_name', models.CharField(blank=True, default='', max_length=100)),
                ('lane', models.CharField(choices=[('config_live', 'This config, live'), ('user_live', "This user's fleet, live"), ('fleet_live', "All users' fleet, live"), ('fleet_paper', 'Fleet paper (haircut)'), ('signal', 'Signal lane (haircut)'), ('unmeasured', 'Unmeasured — conviction x net RR')], default='unmeasured', max_length=12)),
                ('n', models.IntegerField(default=0)),
                ('e_r', models.FloatField(blank=True, null=True)),
                ('p_win', models.FloatField(blank=True, null=True)),
                ('rank_key', models.FloatField(default=0.0)),
                ('measured', models.BooleanField(default=False)),
                ('decaying', models.BooleanField(default=False)),
                ('risk_dollars_default', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('marginal_risk', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('corr_max', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('outcome', models.CharField(choices=[('chosen', 'Chosen at full size'), ('resized', 'Chosen, resized down'), ('displaced', 'Displaced'), ('duplicate', 'Duplicate of a better expression'), ('not_desked', 'Not desked (the lane trades whole)'), ('chosen_then_refused', 'Chosen, then refused at execution')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('size_mult', models.FloatField(default=1.0)),
                ('qty_default', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('qty_final', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('price', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('stop', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('horizon_hours', models.FloatField(default=168.0)),
                ('counterfactual_r', models.FloatField(blank=True, null=True)),
                ('counterfactual_outcome', models.CharField(blank=True, default='', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_decisions', to='bot_program.assetbotconfig')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desk_decisions', to='bot_program.assetbottrade')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='bot_program.deskplan')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='deskplan',
            index=models.Index(fields=['user', 'venue', '-created_at'], name='bot_program_user_id_5ee50d_idx'),
        ),
        migrations.AddIndex(
            model_name='deskplan',
            index=models.Index(fields=['graded_at'], name='bot_program_graded__50ddbd_idx'),
        ),
        migrations.AddIndex(
            model_name='deskdecision',
            index=models.Index(fields=['plan'], name='bot_program_plan_id_1576ee_idx'),
        ),
        migrations.AddIndex(
            model_name='deskdecision',
            index=models.Index(fields=['config', 'symbol', 'created_at'], name='bot_program_config__c1b02f_idx'),
        ),
        migrations.AddIndex(
            model_name='deskdecision',
            index=models.Index(fields=['outcome', 'resolved_at'], name='bot_program_outcome_23f9a7_idx'),
        ),
    ]
