# Generated by Django 5.2.17 on 2026-09-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0028_capital_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskplan',
            name='new_risk_marginal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
