# Generated by Django 5.2.17 on 2026-09-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0029_desk_marginal_risk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtoroAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Main', max_length=60)),
                ('api_key_enc', models.TextField(blank=True)),
                ('user_key_enc', models.TextField(blank=True)),
                ('demo', models.BooleanField(default=True, help_text="Keys for eToro's demo (virtual) portfolio.")),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etoro_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaxoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Main', max_length=60)),
                ('app_key_enc', models.TextField(blank=True)),
                ('app_secret_enc', models.TextField(blank=True)),
                ('redirect_uri', models.CharField(blank=True, max_length=300)),
                ('sim', models.BooleanField(default=True, help_text="Keys registered on Saxo's SIM environment.")),
                ('access_token_enc', models.TextField(blank=True)),
                ('refresh_token_enc', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saxo_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
