# Generated by Django 5.2.17 on 2026-09-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0030_etoroaccount_saxoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoroaccount',
            name='is_primary_for_commodity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='is_primary_for_crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='is_primary_for_forex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='is_primary_for_stocks',
            field=models.BooleanField(default=False, help_text='Route stocks, ETFs and indices here.'),
        ),
    ]
