# Generated by Django 5.2.17 on 2026-09-17 10:54

import django.db.models.deletion
from django.db import migrations, models


def backfill_pair(apps, schema_editor):
    """Every reading written before 2026-09-17 belonged to an IBKRAccount
    through the FK. Give each its pair so no reading loses its owner."""
    Reading = apps.get_model("bot_program", "BrokerEquityReading")
    rows = list(Reading.objects.filter(account_pk__isnull=True)
                .only("id", "account_id"))
    for r in rows:
        r.broker = "ibkr"
        r.account_pk = r.account_id
    if rows:
        Reading.objects.bulk_update(rows, ["broker", "account_pk"],
                                    batch_size=500)


def refuse_reverse_over_readings_without_an_owner(apps, schema_editor):
    """The reverse of this migration puts `account` back to NOT NULL.

    Every reading the Saxo and eToro walks have written since 2026-09-17
    carries no IBKR foreign key (sync_saxo_accounts passes account=None,
    sync_etoro_accounts passes nothing), so the AlterField below, run
    backwards, raised an IntegrityError mid-migration on any box where
    either walk had run — and this RunPython's reverse was a no-op that
    let it get that far (review, 2026-09-28).

    The forward docstring says why the reverse cannot simply delete them:
    "so no reading loses its owner". Those rows ARE readings with owners —
    owners the 0031 schema cannot name. So the reverse REFUSES, here,
    before any column is touched (this operation is last forward and
    therefore first backward), and says which rows and what to do. It
    deletes nothing.
    """
    from collections import Counter

    from django.db.migrations.exceptions import IrreversibleError

    Reading = apps.get_model("bot_program", "BrokerEquityReading")
    by_broker = Counter(Reading.objects.filter(account__isnull=True)
                        .values_list("broker", flat=True))
    if not by_broker:
        return
    n = sum(by_broker.values())
    named = ", ".join(f"{b}: {c}" for b, c in sorted(by_broker.items()))
    raise IrreversibleError(
        f"cannot reverse 0032: {n} BrokerEquityReading rows have no IBKR "
        f"owner ({named}) and 0031's NOT NULL `account` column cannot hold "
        f"them. This reverse deletes nothing, so no reading loses its owner: "
        f"take a dump (deploy/backup.sh), delete or re-key those rows by "
        f"hand, then migrate again.")


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0031_etoroaccount_primary_flags'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brokerequityreading',
            name='one_reading_per_sync',
        ),
        migrations.RemoveIndex(
            model_name='brokerequityreading',
            name='bot_program_account_0153f0_idx',
        ),
        migrations.AddField(
            model_name='brokerequityreading',
            name='account_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerequityreading',
            name='broker',
            field=models.CharField(db_index=True, default='ibkr', max_length=16),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='broker_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='broker_positions_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='last_equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='last_equity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etoroaccount',
            name='last_equity_currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='brokerequityreading',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equity_readings', to='bot_program.ibkraccount'),
        ),
        migrations.AddIndex(
            model_name='brokerequityreading',
            index=models.Index(fields=['broker', 'account_pk', '-at'], name='bot_program_broker_40fbfe_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokerequityreading',
            constraint=models.UniqueConstraint(fields=('broker', 'account_pk', 'at'), name='one_reading_per_sync_v2'),
        ),
        migrations.RunPython(backfill_pair,
                             refuse_reverse_over_readings_without_an_owner),
    ]
