# Generated by Django 5.2.17 on 2026-09-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0032_equity_reading_generic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='saxoaccount',
            name='refresh_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='session_lost_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='session_lost_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
