# Generated by Django 5.2.17 on 2026-09-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0033_saxoaccount_session_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='saxoaccount',
            name='broker_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='broker_positions_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='is_primary_for_commodity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='is_primary_for_crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='is_primary_for_forex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='is_primary_for_stocks',
            field=models.BooleanField(default=False, help_text='Route stock and ETF orders to Saxo.'),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='last_equity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='last_equity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saxoaccount',
            name='last_equity_currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
