# Generated by Django 5.2.17 on 2026-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0034_saxo_venue_cells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saxoaccount',
            name='is_primary_for_stocks',
            field=models.BooleanField(default=False, help_text='Route stock, ETF and index orders to Saxo. An index reaches Saxo as a CFD (CfdOnIndex), the way commodities do.'),
        ),
    ]
