# Generated by Django 5.2.17 on 2026-09-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0036_etoroaccount_margin_cells'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoroaccount',
            name='last_margin_world',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
