# Generated by Django 5.2.17 on 2026-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_program', '0037_etoroaccount_margin_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etoroaccount',
            name='is_primary_for_stocks',
            field=models.BooleanField(default=False, help_text='Route stocks, ETFs and indices here. Measured 2026-09-23: stocks settle real at 1x; every ETF and index position is a CFD (overnight fee, even at 1x); indices carry a 1,000 USD minimum exposure.'),
        ),
        migrations.AlterField(
            model_name='ibkraccount',
            name='is_primary_for_commodity',
            field=models.BooleanField(default=False, help_text="Route commodity orders to IBKR (futures via FUT contracts); Saxo's and eToro's commodity flags win over this one. Since 2026-09-26 a live commodity entry routed here is refused before any order is sent: only eToro carries live commodities."),
        ),
    ]
