# Generated by Django 5.2.17 on 2026-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_program", "0039_withdrawal_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="currency_assumed",
            field=models.BooleanField(default=False),
        ),
    ]
