# Generated by Django 5.2.17 on 2026-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_program", "0040_withdrawalrequest_currency_assumed"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="held_through",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
