# Generated by Django 5.2.17 on 2026-10-01 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_program", "0041_withdrawalrequest_held_through"),
    ]

    operations = [
        migrations.CreateModel(
            name="AragornAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=24)),
                ("rule_name", models.CharField(blank=True, max_length=100)),
                ("asset_class", models.CharField(blank=True, max_length=12)),
                ("symbol", models.CharField(blank=True, max_length=40)),
                ("trade_id", models.IntegerField(blank=True, null=True)),
                ("detail", models.TextField(blank=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("by", models.CharField(default="aragorn", max_length=40)),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="AragornSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, unique=True)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="MarketStressReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("raw_level", models.CharField(blank=True, max_length=12)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("calm", "Calm"),
                            ("stressed", "Stressed"),
                            ("crisis", "Crisis"),
                            ("recovery", "Recovery"),
                        ],
                        max_length=12,
                    ),
                ),
                ("components", models.JSONField(blank=True, default=dict)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("override", models.CharField(blank=True, max_length=12)),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="PairVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(db_index=True, max_length=100)),
                ("asset_class", models.CharField(max_length=12)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("live", "Live"),
                            ("probation", "Probation"),
                            ("bench", "Bench"),
                        ],
                        max_length=12,
                    ),
                ),
                ("since", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField(blank=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("pinned", models.BooleanField(default=False)),
                ("changed_by", models.CharField(default="aragorn", max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rule_name", "asset_class"],
                "unique_together": {("rule_name", "asset_class")},
            },
        ),
    ]
