# Generated by Django 5.2.13 on 2026-04-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tradingrestriction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_969660_idx',
            old_name='core_audit_user_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_d80c2d_idx',
            old_name='core_audit_action_idx',
        ),
    ]
