# Generated by Django 5.2.12 on 2026-08-18 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_core_audit_user_idx_core_auditl_user_id_969660_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('last_ip', models.CharField(blank=True, default='', max_length=64)),
                ('last_path', models.CharField(blank=True, default='', max_length=200)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user presences',
            },
        ),
    ]
