# Generated by Django 5.2.12 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(max_length=10)),
                ('filer_name', models.CharField(max_length=300)),
                ('filing_date', models.DateField()),
                ('shares', models.BigIntegerField(null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20)),
                ('change_pct', models.FloatField(null=True)),
                ('source_url', models.URLField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_filings', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-filing_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('content_summary', models.TextField(blank=True)),
                ('raw_content', models.TextField(blank=True)),
                ('ai_sentiment_score', models.FloatField(blank=True, null=True)),
                ('ai_urgency', models.CharField(blank=True, max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('ai_affected_instruments', models.ManyToManyField(blank=True, related_name='news_articles', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='COTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('commercial_long', models.BigIntegerField()),
                ('commercial_short', models.BigIntegerField()),
                ('non_commercial_long', models.BigIntegerField()),
                ('non_commercial_short', models.BigIntegerField()),
                ('open_interest', models.BigIntegerField()),
                ('net_speculative', models.BigIntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cot_reports', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('instrument', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='SentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('bullish_count', models.IntegerField(default=0)),
                ('bearish_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('composite_score', models.FloatField()),
                ('volume', models.IntegerField(default=0)),
                ('trending', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'source', '-timestamp'], name='scraping_se_instrum_f535f2_idx')],
            },
        ),
    ]
