# Generated by Django 5.2.12 on 2026-03-31 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('contract_type', models.CharField(max_length=4)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expiry', models.DateField()),
                ('volume', models.IntegerField()),
                ('open_interest', models.IntegerField(default=0)),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sentiment', models.CharField(max_length=10)),
                ('is_unusual', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_flow', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
