# Generated by Django 5.0.6 on 2026-08-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_alter_instrument_asset_class'),
        ('scraping', '0002_optionsflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalfiling',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutional_filings', to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
