# Generated by Django 5.2.12 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_horizon', models.CharField(choices=[('scalp', 'Scalp (minutes-hours)'), ('intraday', 'Intraday'), ('swing', 'Swing (days-weeks)'), ('position', 'Position (weeks-months)')], max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('max_portfolio_allocation_pct', models.FloatField(default=10.0)),
                ('max_loss_pct', models.FloatField(default=2.0)),
                ('correlation_constraint', models.TextField(blank=True)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pnl_pct', models.FloatField(default=0)),
                ('max_drawdown', models.FloatField(default=0)),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('source_signals', models.ManyToManyField(blank=True, related_name='strategies', to='signals.signal')),
            ],
            options={
                'verbose_name_plural': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('adjustment_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('applied', models.BooleanField(default=False)),
                ('applied_by', models.CharField(blank=True, max_length=20)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StrategyLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('hedge', 'Hedge')], max_length=10)),
                ('weight', models.FloatField(default=1.0)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('entry_conditions', models.JSONField(default=dict)),
                ('exit_conditions', models.JSONField(default=dict)),
                ('is_entered', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='strategies.strategy')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='instruments',
            field=models.ManyToManyField(through='strategies.StrategyLeg', to='instruments.instrument'),
        ),
    ]
