# Generated by Django 5.0.6 on 2026-05-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0003_alter_instrument_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_label', models.CharField(choices=[('risk_on', 'Risk-on'), ('risk_off', 'Risk-off'), ('mean_reverting', 'Mean-reverting'), ('trending', 'Trending'), ('blow_off', 'Blow-off'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('regime_confidence', models.FloatField(default=0.0)),
                ('portfolio_health_score', models.FloatField(default=0.5)),
                ('top_concerns', models.JSONField(default=list)),
                ('theme_pressures', models.JSONField(default=dict)),
                ('rule_status_overlay', models.JSONField(default=dict)),
                ('narrative_md', models.TextField(blank=True)),
                ('model_used', models.CharField(default='', max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('n_observations_consumed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='brain_brain_created_58e3f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BrainObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('source_agent', models.CharField(default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consumed_by_brain_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_observations', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='brain_brain_kind_86154c_idx'), models.Index(fields=['consumed_by_brain_at', '-created_at'], name='brain_brain_consume_f721ec_idx')],
            },
        ),
    ]
