# Generated by Django 5.0.6 on 2026-05-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0006_agentprediction_expected_resolution_at_and_more'),
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_observations_pruned', models.IntegerField(default=0)),
                ('n_hypotheses_resolved', models.IntegerField(default=0)),
                ('n_nodes_added', models.IntegerField(default=0)),
                ('n_nodes_superseded', models.IntegerField(default=0)),
                ('n_critics_invoked', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.CharField(help_text='Human-readable claim.', max_length=400)),
                ('claim_payload', models.JSONField(default=dict, help_text='Structured claim — used by resolver.')),
                ('resolution_criteria', models.JSONField(default=dict, help_text='Resolver-readable spec: how to grade.')),
                ('confidence', models.FloatField(default=0.5)),
                ('source_agent', models.CharField(db_index=True, max_length=80)),
                ('resolution_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('refuted', 'Refuted'), ('unresolvable', 'Unresolvable')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses', to='ai_agents.agentprediction')),
                ('brain_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses', to='brain.brainreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HypothesisVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(db_index=True, max_length=80)),
                ('stance', models.CharField(choices=[('co_sign', 'Co-sign'), ('dissent', 'Dissent'), ('refine', 'Refine')], max_length=20)),
                ('confidence', models.FloatField(default=0.5)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='brain.hypothesis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.5)),
                ('source_agents', models.JSONField(default=list, help_text='Agents that contributed to this version.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='brain.knowledgenode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hypothesis',
            index=models.Index(fields=['source_agent', '-created_at'], name='brain_hypot_source__3a6c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesis',
            index=models.Index(fields=['outcome', 'resolution_deadline'], name='brain_hypot_outcome_2ca7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='hypothesisvote',
            index=models.Index(fields=['agent', '-created_at'], name='brain_hypot_agent_4c637f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hypothesisvote',
            unique_together={('hypothesis', 'agent')},
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['kind', 'key', '-version'], name='brain_knowl_kind_b3bf24_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['kind', 'key', 'superseded_by'], name='brain_knowl_kind_c574ee_idx'),
        ),
    ]
