# Generated by Django 5.0.6 on 2026-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_consolidationrun_hypothesis_hypothesisvote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategistBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlook_md', models.TextField(blank=True)),
                ('posture', models.CharField(choices=[('defensive', 'Defensive'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
                ('posture_rationale', models.CharField(blank=True, max_length=500)),
                ('watchlist', models.JSONField(default=list)),
                ('ideas', models.JSONField(default=list)),
                ('model_used', models.CharField(default='', max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='brain_strat_created_7b7d2a_idx')],
            },
        ),
    ]
