# Generated by Django 5.0.6 on 2026-05-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_strategistbriefing'),
        ('signals', '0014_fastevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSetupProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(db_index=True, max_length=120)),
                ('rationale_md', models.TextField(blank=True, help_text='Markdown rationale from the generator agent.')),
                ('inspiration_summary', models.CharField(blank=True, help_text='What in the graph/track-record inspired this proposal.', max_length=300)),
                ('direction', models.CharField(default='bullish', max_length=10)),
                ('asset_classes', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('min_match_score', models.FloatField(default=0.6)),
                ('suggested_horizon_days', models.IntegerField(default=5)),
                ('sizing', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, help_text='Username of admin who decided.', max_length=80)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('model_used', models.CharField(default='', max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hypothesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_proposals', to='brain.hypothesis')),
                ('rule_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_proposals', to='signals.rulecontrol')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_proposals', to='signals.opportunitysetup')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='brain_gener_status_f14323_idx')],
            },
        ),
    ]
