# Generated by Django 5.0.6 on 2026-05-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_generatedsetupproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDemotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=120)),
                ('criterion', models.CharField(choices=[('hypothesis_refuted', 'Hypothesis refuted'), ('sustained_negative', 'Sustained negative avg_r'), ('consecutive_losses', 'Consecutive losses'), ('manual', 'Manual')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('metrics', models.JSONField(default=dict)),
                ('demoted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restored_at', models.DateTimeField(blank=True, help_text='If admin re-enabled the rule.', null=True)),
                ('restored_by', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-demoted_at'],
                'indexes': [models.Index(fields=['rule_name', '-demoted_at'], name='brain_ruled_rule_na_f1fea4_idx'), models.Index(fields=['restored_at', '-demoted_at'], name='brain_ruled_restore_6ca333_idx')],
            },
        ),
    ]
