# Generated by Django 5.0.6 on 2026-05-07 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_ruledemotion'),
        ('instruments', '0003_alter_instrument_asset_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(blank=True, max_length=300)),
                ('event_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('summary_md', models.TextField(blank=True, help_text='2-4 paragraph narrative.')),
                ('key_themes', models.JSONField(default=list, help_text='Top themes (list of {kind, text, severity}).')),
                ('risk_signals', models.JSONField(default=list, help_text='Specific bear-case items the reviewer flagged.')),
                ('implied_direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('implied_confidence', models.FloatField(default=0.5)),
                ('suggested_action', models.CharField(blank=True, help_text="One-line operator nudge (e.g. 'tighten stop', 'reduce size').", max_length=300)),
                ('input_news_count', models.IntegerField(default=0)),
                ('input_price_move_pct', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(default='', max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_reviews', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instrument', '-event_datetime'], name='brain_earni_instrum_888c67_idx'), models.Index(fields=['-created_at'], name='brain_earni_created_1c000f_idx')],
            },
        ),
    ]
