# Generated by Django 5.0.6 on 2026-05-07 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_earningsreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Auto-generated from the first user message.', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one active conversation per user.')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='brain.researchconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchconversation',
            index=models.Index(fields=['user', '-last_message_at'], name='brain_resea_user_id_5cbe11_idx'),
        ),
        migrations.AddIndex(
            model_name='researchconversation',
            index=models.Index(fields=['user', 'is_active'], name='brain_resea_user_id_b4c4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='researchmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='brain_resea_convers_4edae1_idx'),
        ),
    ]
