# Generated by Django 5.2.12 on 2026-08-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_researchconversation_researchmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmessage',
            name='replies_to',
            field=models.ForeignKey(blank=True, help_text='For an assistant row: the user message it answers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='brain.researchmessage'),
        ),
        migrations.AddField(
            model_name='researchmessage',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], db_index=True, default='done', help_text='Assistant rows are born PENDING and filled in place by the worker that answers them.', max_length=12),
        ),
    ]
