# Generated by Django 5.2.12 on 2026-08-19 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0008_researchmessage_replies_to_researchmessage_status'),
        ('instruments', '0003_alter_instrument_asset_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(choices=[('bot', 'Asset bot trade'), ('pf', 'Portfolio position')], db_index=True, max_length=4)),
                ('position_id', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=40)),
                ('side', models.CharField(blank=True, max_length=4)),
                ('triggers', models.JSONField(default=list, help_text='List of {code, severity, text, values} — the reasons that fired.')),
                ('facts', models.JSONField(default=dict, help_text='The full measured fact block the triggers were read from.')),
                ('facts_hash', models.CharField(blank=True, db_index=True, help_text='Fingerprint of the BUCKETED facts — the dedupe key for the model pass. Raw floats would change every tick and defeat it.', max_length=64)),
                ('severity', models.FloatField(default=0.0, help_text='Max severity across fired triggers, 0..1.')),
                ('stale_quote', models.BooleanField(default=False, help_text='True when no usable mark existed. No verdict is computed on a stale mark — the row exists to say so out loud.')),
                ('mark', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('unrealized_r', models.FloatField(blank=True, null=True)),
                ('r_to_stop', models.FloatField(blank=True, help_text='R still at risk between the mark and the CURRENT stop.', null=True)),
                ('r_to_target', models.FloatField(blank=True, null=True)),
                ('mae_r', models.FloatField(blank=True, help_text='Worst excursion since entry, in R.', null=True)),
                ('mfe_r', models.FloatField(blank=True, help_text='Best excursion since entry, in R.', null=True)),
                ('age_hours', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('hold', 'Hold'), ('tighten', 'Tighten the stop'), ('take_part', 'Take part off'), ('exit', 'Exit'), ('none', 'No verdict (model pass not made)'), ('no_quote', 'No verdict (no usable mark)')], db_index=True, default='none', max_length=12)),
                ('reasoning_md', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('suggested_stop', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_part_pct', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('skipped_reason', models.CharField(blank=True, help_text='Why no model pass was made (budget, per-pass cap, same facts).', max_length=200)),
                ('error', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('graded_outcome', models.CharField(blank=True, choices=[('right', 'Recommendation helped'), ('wrong', 'Recommendation hurt'), ('unresolvable', 'Could not be measured')], db_index=True, max_length=14)),
                ('grading_notes', models.CharField(blank=True, max_length=300)),
                ('r_at_review', models.FloatField(blank=True, null=True)),
                ('r_at_close', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hypothesis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_reviews', to='brain.hypothesis')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_reviews', to='instruments.instrument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['book', 'position_id', '-created_at'], name='brain_posit_book_75717c_idx'), models.Index(fields=['-created_at'], name='brain_posit_created_fcd43c_idx'), models.Index(fields=['verdict', '-created_at'], name='brain_posit_verdict_063e20_idx')],
            },
        ),
    ]
