# Generated by Django 5.2.17 on 2026-09-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_positionreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorizonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'OK'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, default='running', max_length=12)),
                ('horizon_years', models.IntegerField(default=5)),
                ('summary_md', models.TextField(blank=True)),
                ('sectors', models.JSONField(default=list)),
                ('asset_class_tilts', models.JSONField(default=dict)),
                ('regime_claims', models.JSONField(default=list)),
                ('calls_registered', models.IntegerField(default=0)),
                ('calls_dropped', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='', max_length=80)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error', models.TextField(blank=True)),
                ('raw', models.TextField(blank=True)),
                ('snapshot_as_of', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
