# Generated by Django 5.2.12 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('impact', models.CharField(max_length=10)),
                ('actual', models.CharField(blank=True, max_length=50)),
                ('forecast', models.CharField(blank=True, max_length=50)),
                ('previous', models.CharField(blank=True, max_length=50)),
                ('currency_affected', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=20)),
                ('last_value', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('last_date', models.DateField(null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LiveQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('last', models.DecimalField(decimal_places=8, max_digits=20)),
                ('change_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('volume', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=50)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_quote', to='instruments.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='MacroObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='market_data.macroindicator')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('indicator', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week')], max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.BigIntegerField(default=0)),
                ('source', models.CharField(max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='market_data_instrum_b8c366_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
    ]
