# Generated by Django 5.2.13 on 2026-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_live_extras'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fundingrate',
            new_name='market_data_symbol_51aafb_idx',
            old_name='md_fund_sym_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='liquidationevent',
            new_name='market_data_symbol_4ab28e_idx',
            old_name='md_liq_sym_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='orderbooksnapshot',
            new_name='market_data_symbol_f3fac4_idx',
            old_name='md_ob_sym_ts_idx',
        ),
        migrations.AlterField(
            model_name='fundingrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='liquidationevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderbooksnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
