# Generated by Django 5.2.12 on 2026-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_class', models.CharField(choices=[('stock', 'Stock'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond')], max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_watchlist', models.BooleanField(default=False)),
                ('trading_hours', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_class', 'symbol'],
            },
        ),
    ]
