# Generated by Django 5.0.6 on 2026-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stock'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond'), ('options', 'Options')], max_length=20),
        ),
    ]
