# Generated by Django 5.0.6 on 2026-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_asset_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='asset_class',
            field=models.CharField(choices=[('stock', 'Stock'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('index', 'Index'), ('etf', 'ETF'), ('crypto', 'Cryptocurrency'), ('bond', 'Bond'), ('options', 'Options'), ('cfd', 'CFD')], max_length=20),
        ),
    ]
