# Generated by Django 5.2.12 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('sma_20', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('sma_50', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('sma_200', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ema_12', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('ema_26', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('rsi_14', models.FloatField(null=True)),
                ('macd_line', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('macd_histogram', models.FloatField(null=True)),
                ('stoch_k', models.FloatField(null=True)),
                ('stoch_d', models.FloatField(null=True)),
                ('bollinger_upper', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('bollinger_lower', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('atr_14', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('obv', models.BigIntegerField(null=True)),
                ('vwap', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicals', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instrument', 'timeframe', '-timestamp'], name='indicators__instrum_5cfe52_idx')],
                'unique_together': {('instrument', 'timeframe', 'timestamp')},
            },
        ),
    ]
