# Generated by Django 5.2.12 on 2026-04-05 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('instrument_symbol', models.CharField(blank=True, max_length=20)),
                ('asset_class', models.CharField(blank=True, max_length=20)),
                ('min_score', models.FloatField(default=0.5)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('urgency', models.CharField(blank=True, max_length=10)),
                ('notify_telegram', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('notify_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('adhoc', 'Ad-hoc')], default='weekly', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_generated', 'AI Generated — Pending Review'), ('approved', 'Approved'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=15)),
                ('content_markdown', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('ai_prompt', models.TextField(blank=True, help_text='Prompt used to generate content')),
                ('send_telegram', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('target_all_users', models.BooleanField(default=True)),
                ('target_markets', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_number', models.CharField(blank=True, max_length=20)),
                ('receive_signals', models.BooleanField(default=True)),
                ('receive_strategies', models.BooleanField(default=True)),
                ('receive_news_alerts', models.BooleanField(default=True)),
                ('receive_portfolio_alerts', models.BooleanField(default=True)),
                ('receive_weekly_newsletter', models.BooleanField(default=True)),
                ('receive_monthly_newsletter', models.BooleanField(default=True)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User notification preferences',
            },
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
