# Generated by Django 5.0.6 on 2026-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_webhookendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationprefs',
            name='receive_bot_alerts',
            field=models.BooleanField(default=True, help_text='Bot fills, orchestrator gate rejections, drawdown limit warnings.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('signal', 'New Signal'), ('strategy', 'Strategy Update'), ('news', 'Breaking News'), ('portfolio', 'Portfolio Alert'), ('system', 'System Message'), ('newsletter', 'Newsletter'), ('bot', 'Bot Event')], max_length=20),
        ),
    ]
