# Generated by Django 5.0.6 on 2026-05-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_usernotificationprefs_receive_bot_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationprefs',
            name='receive_strategist_briefing',
            field=models.BooleanField(default=False, help_text="Daily Sauron's Mind strategist briefing — outlook + posture + ideas."),
        ),
    ]
