# Generated by Django 5.2.12 on 2026-08-18 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_usernotificationprefs_receive_strategist_briefing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='alerts_noti_user_id_f18f0e_idx'),
        ),
    ]
