# Generated by Django 5.2.12 on 2026-08-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('signal', 'New Signal'), ('strategy', 'Strategy Update'), ('news', 'Breaking News'), ('portfolio', 'Portfolio Alert'), ('system', 'System Message'), ('newsletter', 'Newsletter'), ('bot', 'Bot Event'), ('briefing', 'Sauron Briefing')], max_length=20),
        ),
    ]
