# Generated by Django 5.2.17 on 2026-09-29 07:34
#
# The weekly letter (2026-09-29): the schedule, the send's lease and
# queued request, the ledger (NewsletterDelivery), the unsubscribe
# token's random value, and where an edition came from. The review of
# 2026-09-29 folded its fields (origin, send_requested_at, touched_at,
# NewsletterDelivery.address and the "sending"/"unknown" statuses,
# UserNotificationPrefs.newsletter_token) into this migration: it had not
# shipped.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_weekly_reviews(apps, schema_editor):
    """The rows generate_weekly_review wrote before the letter had an
    origin ("Sauron Vision Weekly Review — Week of ..."): the Monday plan
    keeps reading the latest of them until a new Saturday writes one."""
    Newsletter = apps.get_model("alerts", "Newsletter")
    Newsletter.objects.filter(
        frequency="weekly",
        title__startswith="Sauron Vision Weekly Review").update(
            origin="weekly_review")


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0012_pricealert_baseline_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="last_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly_review", "Saturday weekly review"),
                    ("admin", "Admin page"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="send_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="send_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="touched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernotificationprefs",
            name="newsletter_token",
            field=models.CharField(
                blank=True, editable=False, max_length=40, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("generating", "Generating"),
                    ("ai_generated", "Ready"),
                    ("approved", "Approved"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("unknown", "Outcome unknown"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("address", models.CharField(blank=True, max_length=254)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="alerts.newsletter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["newsletter_id", "user_id"],
                "indexes": [
                    models.Index(
                        fields=["newsletter", "status"],
                        name="alerts_news_newslet_24d1c5_idx",
                    )
                ],
                "unique_together": {("newsletter", "user", "channel")},
            },
        ),
        migrations.RunPython(mark_weekly_reviews, migrations.RunPython.noop),
    ]
