# Generated by Django 5.2.12 on 2026-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('news_analyst', 'News Analyst'), ('strategy_advisor', 'Strategy Advisor'), ('weekly_reviewer', 'Weekly Reviewer'), ('anomaly_detector', 'Anomaly Detector'), ('earnings_analyst', 'Earnings Analyst'), ('macro_interpreter', 'Macro Interpreter'), ('monday_planner', 'Monday Planner')], max_length=30)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('prompt_summary', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('response_summary', models.TextField(blank=True)),
                ('structured_output', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
