# Generated by Django 5.2.12 on 2026-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(db_index=True, max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('confidence', models.FloatField(default=0.5)),
                ('source_task_id', models.IntegerField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
    ]
