# Generated by Django 5.2.13 on 2026-04-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_agentprediction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentprediction',
            new_name='ai_agents_a_agent_42b76f_idx',
            old_name='ai_agents_a_agent_created_idx',
        ),
    ]
