# Generated by Django 5.0.6 on 2026-04-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0004_rename_ai_agents_a_agent_created_idx_ai_agents_a_agent_42b76f_idx'),
        ('bot_program', '0004_alter_botcircuitstate_id_alter_botheartbeat_id_and_more'),
        ('portfolio', '0004_traderprofile_access_pin_hash'),
        ('signals', '0006_signal_performance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecayInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100)),
                ('recent_expectancy', models.FloatField(blank=True, null=True)),
                ('baseline_expectancy', models.FloatField(blank=True, null=True)),
                ('recent_n', models.IntegerField(default=0)),
                ('baseline_n', models.IntegerField(default=0)),
                ('hypothesis', models.TextField(blank=True)),
                ('contributing_factors', models.JSONField(default=list)),
                ('recommended_action', models.CharField(blank=True, max_length=400)),
                ('structured_output', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decay_investigations', to='ai_agents.agenttask')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rule_name', '-created_at'], name='ai_agents_d_rule_na_388105_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], default='N/A', max_length=4)),
                ('summary', models.TextField(blank=True)),
                ('key_takeaway', models.CharField(blank=True, max_length=400)),
                ('lessons', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('emotional_state', models.CharField(blank=True, max_length=20)),
                ('structured_output', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='ai_agents.agenttask')),
                ('bot_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='bot_program.bottrade')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='portfolio.position')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='signals.signal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ai_agents_t_created_931909_idx'), models.Index(fields=['grade', '-created_at'], name='ai_agents_t_grade_e16e56_idx')],
            },
        ),
    ]
