# Generated by Django 5.0.6 on 2026-05-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0005_decayinvestigation_tradejournalentry'),
        ('signals', '0007_rulecontrol_ruleaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprediction',
            name='expected_resolution_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Earliest time ground truth is expected.', null=True),
        ),
        migrations.AddField(
            model_name='agentprediction',
            name='linked_rule_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_predictions', to='signals.ruleaction'),
        ),
        migrations.AddField(
            model_name='agentprediction',
            name='linked_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_predictions', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='agentprediction',
            name='score',
            field=models.FloatField(blank=True, help_text='Granular correctness; for trade outcomes = realized_r.', null=True),
        ),
        migrations.AlterField(
            model_name='agentprediction',
            name='confidence',
            field=models.FloatField(default=0.5, help_text='Probability assigned to predicted_value (0.0–1.0).'),
        ),
        migrations.AddIndex(
            model_name='agentprediction',
            index=models.Index(fields=['was_correct', 'expected_resolution_at'], name='ai_agents_a_was_cor_47b906_idx'),
        ),
    ]
