# Generated by Django 5.2.12 on 2026-08-08 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0006_agentprediction_expected_resolution_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('tier', 'Tier'), ('agent', 'Agent')], max_length=8)),
                ('key', models.CharField(max_length=60)),
                ('model_id', models.CharField(blank=True, max_length=60)),
                ('effort', models.CharField(blank=True, default='', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_model_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'key'],
                'unique_together': {('scope', 'key')},
            },
        ),
    ]
