# Generated by Django 5.2.12 on 2026-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0007_aimodelsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='agent',
            field=models.CharField(max_length=30),
        ),
    ]
