# Generated by Django 5.2.17 on 2026-09-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0008_agent_names_are_free_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprediction',
            name='horizon_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprediction',
            name='reference_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
