# Generated by Django 5.2.17 on 2026-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0009_agentprediction_direction_calls"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["-created_at"], name="agenttask_created_desc"),
        ),
    ]
