# Generated by Django 5.2.12 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main', max_length=100)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_available', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('max_total_exposure_pct', models.FloatField(default=100)),
                ('max_single_position_pct', models.FloatField(default=10)),
                ('max_sector_exposure_pct', models.FloatField(default=30)),
                ('max_correlation_threshold', models.FloatField(default=0.7)),
                ('max_daily_loss_pct', models.FloatField(default=3.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pnl_pct', models.FloatField(default=0)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('daily_pnl_pct', models.FloatField()),
                ('cumulative_pnl_pct', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('exposure_by_asset_class', models.JSONField(default=dict)),
                ('exposure_by_sector', models.JSONField(default=dict)),
                ('exposure_by_currency', models.JSONField(default=dict)),
                ('correlation_matrix', models.JSONField(default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('portfolio', 'date')},
            },
        ),
    ]
