# Generated by Django 4.2.29 on 2026-03-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short bio or trading motto')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('timezone_preference', models.CharField(default='UTC', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (< 1 year)'), ('intermediate', 'Intermediate (1–3 years)'), ('advanced', 'Advanced (3–7 years)'), ('expert', 'Expert (7+ years)'), ('professional', 'Professional / Institutional')], default='intermediate', max_length=20)),
                ('trading_style', models.CharField(choices=[('scalper', 'Scalper (seconds–minutes)'), ('day_trader', 'Day Trader (intraday)'), ('swing_trader', 'Swing Trader (days–weeks)'), ('position_trader', 'Position Trader (weeks–months)'), ('investor', 'Long-Term Investor (months–years)'), ('hybrid', 'Hybrid / Multi-timeframe')], default='swing_trader', max_length=20)),
                ('risk_appetite', models.CharField(choices=[('conservative', 'Conservative — Capital preservation first'), ('moderate', 'Moderate — Balanced growth and safety'), ('aggressive', 'Aggressive — High returns, accept volatility'), ('very_aggressive', 'Very Aggressive — Maximum growth, high risk tolerance')], default='moderate', max_length=20)),
                ('analysis_approach', models.CharField(choices=[('technical', 'Primarily Technical Analysis'), ('fundamental', 'Primarily Fundamental Analysis'), ('quantitative', 'Quantitative / Algorithmic'), ('sentiment', 'Sentiment / News-Driven'), ('mixed', 'Mixed Approach')], default='mixed', max_length=20)),
                ('trade_stocks', models.BooleanField(default=True)),
                ('trade_forex', models.BooleanField(default=True)),
                ('trade_commodities', models.BooleanField(default=True)),
                ('trade_crypto', models.BooleanField(default=False)),
                ('trade_indices', models.BooleanField(default=False)),
                ('trade_bonds', models.BooleanField(default=False)),
                ('preferred_session', models.CharField(choices=[('asian', 'Asian Session (Tokyo)'), ('european', 'European Session (London)'), ('american', 'American Session (New York)'), ('all', 'All Sessions')], default='european', max_length=20)),
                ('available_hours_per_day', models.FloatField(default=2.0, help_text='Hours per day available for trading')),
                ('monthly_return_target_pct', models.FloatField(default=3.0)),
                ('max_acceptable_drawdown_pct', models.FloatField(default=10.0)),
                ('annual_income_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notify_signals', models.BooleanField(default=True, help_text='Get alerts for new trading signals')),
                ('notify_strategies', models.BooleanField(default=True, help_text='Get alerts for strategy proposals')),
                ('notify_news_critical', models.BooleanField(default=True, help_text='Get alerts for critical market news')),
                ('notify_portfolio', models.BooleanField(default=True, help_text='Get alerts for portfolio changes')),
                ('notify_weekly_review', models.BooleanField(default=True, help_text='Receive weekly AI review')),
                ('notify_channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('discord', 'Discord'), ('none', 'No notifications')], default='telegram', max_length=20)),
                ('ai_autonomy', models.CharField(choices=[('observe', 'Observe Only — AI watches, I decide everything'), ('suggest', 'Suggest — AI proposes, I approve/reject'), ('semi_auto', 'Semi-Auto — AI executes low-risk, I approve high-risk'), ('full_auto', 'Full Auto — AI manages within my risk parameters')], default='suggest', max_length=20)),
                ('ai_commentary_detail', models.CharField(choices=[('brief', 'Brief — Key points only'), ('detailed', 'Detailed — Full analysis with reasoning'), ('comprehensive', 'Comprehensive — Deep dive with alternatives')], default='detailed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trader Profile',
                'verbose_name_plural': 'Trader Profiles',
            },
        ),
    ]
