# Generated by Django 5.2.12 on 2026-03-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_traderprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode')], default='dark', max_length=10),
        ),
    ]
