# Generated by Django 4.2.29 on 2026-04-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_traderprofile_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='access_pin_hash',
            field=models.CharField(blank=True, default='', help_text='Hashed PIN code (2nd-factor)', max_length=128),
        ),
    ]
