# Generated by Django 5.0.6 on 2026-05-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_traderprofile_access_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='cross_asset_orchestrator_enabled',
            field=models.BooleanField(default=False, help_text='Refuse new bot entries that stack same-theme exposure across asset classes.'),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='max_equity_theme_exposure',
            field=models.FloatField(default=3.0, help_text='Max |net equity-beta units| across open positions. Each position contributes ±1.'),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='max_usd_theme_exposure',
            field=models.FloatField(default=3.0, help_text='Max |net USD-theme units| across open positions. Each position contributes ±1.'),
        ),
    ]
