# Generated by Django 5.0.6 on 2026-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_traderprofile_cross_asset_orchestrator_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='max_currency_exposure',
            field=models.FloatField(default=0.0, help_text='Max |net exposure| to any single currency from forex pairs. 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='max_sector_exposure',
            field=models.IntegerField(default=0, help_text='Max concurrent stock/option positions in any single sector. 0 = disabled.'),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='max_vol_theme_exposure',
            field=models.FloatField(default=0.0, help_text='Max long-volatility (long-premium options) positions stacked. 0 = disabled.'),
        ),
    ]
