# Generated by Django 5.0.6 on 2026-05-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_traderprofile_max_currency_exposure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='size_weighted_orchestrator',
            field=models.BooleanField(default=False, help_text='Weight orchestrator theme contributions by position notional. Off = each position contributes ±1.'),
        ),
    ]
