# Generated by Django 5.0.6 on 2026-05-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_traderprofile_size_weighted_orchestrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='tax_lot_method',
            field=models.CharField(choices=[('FIFO', 'FIFO — First In, First Out (US default)'), ('LIFO', 'LIFO — Last In, First Out'), ('HIFO', 'HIFO — Highest Cost In, First Out (tax-loss optimal)')], default='FIFO', help_text='Lot-consumption order on sales for cost-basis bookkeeping.', max_length=4),
        ),
    ]
