# Generated by Django 5.2.12 on 2026-08-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_traderprofile_tax_lot_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='tour_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the guided platform tour was finished or skipped. Null = show once on next login.', null=True),
        ),
    ]
