# Generated by Django 5.2.12 on 2026-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_traderprofile_tour_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='idle_lock_enabled',
            field=models.BooleanField(default=True, help_text='Lock the session behind the PIN after a period of inactivity.'),
        ),
        migrations.AddField(
            model_name='traderprofile',
            name='idle_lock_minutes',
            field=models.PositiveSmallIntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour')], default=10, help_text='Minutes of inactivity before the PIN lock engages.'),
        ),
    ]
