# Generated by Django 5.2.12 on 2026-08-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_single_position_default_agrees_with_sizing'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='max_theme_legs',
            field=models.IntegerField(default=3),
        ),
    ]
