# Generated by Django 5.2.12 on 2026-08-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_theme_leg_cap_on_the_limits_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderprofile',
            name='pages_seen',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
