# Generated by Django 5.2.12 on 2026-08-24 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_the_pages_the_operator_has_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="What the panel calls this book — 'Fund A', a mandate name — instead of the internal username.", max_length=120)),
                ('show_positions', models.BooleanField(default=False, help_text='Open positions, symbol by symbol.')),
                ('show_history', models.BooleanField(default=False, help_text='Closed trades and realized outcomes.')),
                ('percents_only', models.BooleanField(default=True, help_text="Performance without size: percentages and the curve's shape, never dollar amounts.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_access', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
