# Generated by Django 5.2.17 on 2026-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_the_investors_window"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="max_pledged_pct",
            field=models.FloatField(default=50),
        ),
    ]
