# Generated by Django 5.2.17 on 2026-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_portfolio_max_pledged_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="max_open_risk_pct",
            field=models.FloatField(default=15),
        ),
    ]
