# Generated by Django 5.2.12 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('technical', 'Technical'), ('fundamental', 'Fundamental'), ('sentiment', 'Sentiment'), ('macro', 'Macro'), ('flow', 'Institutional Flow'), ('ai_generated', 'AI Generated'), ('composite', 'Composite')], max_length=20)),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=10)),
                ('urgency', models.CharField(choices=[('critical', 'Critical — Act Now'), ('high', 'High — Act Today'), ('medium', 'Medium — Watch Closely'), ('low', 'Low — On Radar')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('rule_name', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('sub_scores', models.JSONField(default=dict)),
                ('price_at_signal', models.DecimalField(decimal_places=8, max_digits=20)),
                ('suggested_entry', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('suggested_stop', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('suggested_target', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('risk_reward_ratio', models.FloatField(null=True)),
                ('portfolio_impact', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(null=True)),
                ('outcome', models.CharField(blank=True, choices=[('hit_target', 'Hit Target'), ('stopped_out', 'Stopped Out'), ('expired', 'Expired'), ('manual_close', 'Manually Closed')], max_length=20)),
                ('conflicts_with', models.ManyToManyField(blank=True, to='signals.signal')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='signals_sig_created_996097_idx'), models.Index(fields=['instrument', 'is_active'], name='signals_sig_instrum_9f56be_idx')],
            },
        ),
    ]
