# Generated by Django 5.2.13 on 2026-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_smcsignal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smcsignal',
            new_name='signals_smc_symbol_78bcf9_idx',
            old_name='signals_smc_symbol_tf_status_idx',
        ),
        migrations.RenameIndex(
            model_name='smcsignal',
            new_name='signals_smc_setup_e2267f_idx',
            old_name='signals_smc_setup_status_idx',
        ),
        migrations.AlterField(
            model_name='smcsignal',
            name='direction',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=8),
        ),
        migrations.AlterField(
            model_name='smcsignal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smcsignal',
            name='setup',
            field=models.CharField(choices=[('RP_BREAKER', 'RP Breaker'), ('THREE_TAP', 'Three Tap'), ('RANGE_MSB_SD', 'Range + MSB + SD'), ('REVERSAL_PATTERN', 'Reversal Pattern'), ('PO3', 'Power of Three'), ('FVG_TAP', 'FVG Tap'), ('OB_RETEST', 'Order Block Retest'), ('SFP', 'Swing Failure Pattern')], max_length=32),
        ),
        migrations.AlterField(
            model_name='smcsignal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIGGERED', 'Triggered'), ('FILLED', 'Filled'), ('STOPPED', 'Stopped'), ('TARGET_HIT', 'Target Hit'), ('EXPIRED', 'Expired'), ('INVALIDATED', 'Invalidated')], default='ACTIVE', max_length=16),
        ),
    ]
