# Generated by Django 5.2.13 on 2026-04-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_rename_signals_smc_symbol_tf_status_idx_signals_smc_symbol_78bcf9_idx_and_more'),
        ('signals', '0003_smcsignal_lifecycle_index'),
    ]

    operations = [
    ]
