# Generated by Django 5.2.13 on 2026-04-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_merge_20260409_1648'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='smcsignal',
            name='signals_smc_status_created_idx',
        ),
    ]
