# Generated by Django 5.0.6 on 2026-05-01 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0005_decayinvestigation_tradejournalentry'),
        ('signals', '0006_signal_performance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('reduced', 'Reduced size')], default='active', max_length=12)),
                ('weight_multiplier', models.FloatField(default=1.0, help_text="Applied to the signal's score / position-sizing weight. 1.0 = full, 0.5 = half.")),
                ('paused_until', models.DateTimeField(blank=True, help_text='When set, status reverts to active automatically after this time.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_name'],
            },
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('pause_rule', 'Pause rule'), ('reduce_size', 'Reduce size'), ('monitor', 'Monitor (no-op)'), ('investigate_data', 'Investigate data quality'), ('retune_params', 'Retune parameters')], max_length=24)),
                ('state', models.CharField(choices=[('proposed', 'Proposed (awaiting admin)'), ('applied', 'Applied'), ('rejected', 'Rejected by admin'), ('rolled_back', 'Rolled back'), ('expired', 'Expired (no decision)')], db_index=True, default='proposed', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=12)),
                ('previous_weight', models.FloatField(blank=True, null=True)),
                ('previous_paused_until', models.DateTimeField(blank=True, null=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_actions_confirmed', to=settings.AUTH_USER_MODEL)),
                ('source_investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_actions', to='ai_agents.decayinvestigation')),
            ],
            options={
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['state', '-proposed_at'], name='signals_rul_state_93d670_idx'), models.Index(fields=['rule_name', '-proposed_at'], name='signals_rul_rule_na_cc2d44_idx')],
            },
        ),
    ]
