# Generated by Django 5.0.6 on 2026-05-01 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_rulecontrol_ruleaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecontrol',
            name='allocator_weight',
            field=models.FloatField(default=1.0, help_text='Phase-7 meta-allocator weight. 1.0 = neutral. Auto-updated.'),
        ),
        migrations.AlterField(
            model_name='rulecontrol',
            name='weight_multiplier',
            field=models.FloatField(default=1.0, help_text='Phase-5 admin-controlled multiplier. 1.0 = full, 0.5 = half.'),
        ),
        migrations.CreateModel(
            name='MetaAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('shadow', 'Shadow (preview)'), ('applied', 'Applied'), ('rolled_back', 'Rolled back'), ('rejected', 'Rejected by admin')], db_index=True, default='shadow', max_length=16)),
                ('lookback_days', models.IntegerField(default=180)),
                ('sample_tier', models.CharField(blank=True, help_text='tier1 (≥30/rule) | tier2 (≥10/rule) | tier3 (<10)', max_length=10)),
                ('ensemble_blend', models.JSONField(default=dict)),
                ('per_method_weights', models.JSONField(default=dict)),
                ('target_weights', models.JSONField(default=dict)),
                ('previous_weights', models.JSONField(default=dict)),
                ('rules_considered', models.IntegerField(default=0)),
                ('rules_skipped', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_allocations_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['state', '-proposed_at'], name='signals_met_state_c54cbd_idx')],
            },
        ),
    ]
