# Generated by Django 5.0.6 on 2026-05-01 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_rulecontrol_allocator_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecontrol',
            name='promotion_stage',
            field=models.CharField(choices=[('research', 'Research (no trade)'), ('paper', 'Paper only'), ('live_small', 'Live (small size)'), ('live_full', 'Live (full size)')], default='live_full', help_text='Phase-8 promotion stage. New rules start at RESEARCH; existing migrate at LIVE_FULL.', max_length=16),
        ),
        migrations.AddField(
            model_name='rulecontrol',
            name='stage_baseline_expectancy',
            field=models.FloatField(blank=True, help_text='Expectancy at last stage transition; used to detect degradation for auto-demote.', null=True),
        ),
        migrations.AddField(
            model_name='rulecontrol',
            name='stage_entered_at',
            field=models.DateTimeField(blank=True, help_text='When the rule entered its current promotion_stage.', null=True),
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(db_index=True, max_length=100)),
                ('from_stage', models.CharField(blank=True, max_length=16)),
                ('to_stage', models.CharField(max_length=16)),
                ('reason', models.CharField(choices=[('auto_promote', 'Auto promotion (criteria met)'), ('auto_demote', 'Auto demotion (degradation)'), ('manual_promote', 'Manual promotion'), ('manual_demote', 'Manual demotion'), ('rollback', 'Rollback to prior stage')], max_length=24)),
                ('expectancy_at_transition', models.FloatField(blank=True, null=True)),
                ('n_at_transition', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_events_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rule_name', '-created_at'], name='signals_pro_rule_na_642a77_idx')],
            },
        ),
    ]
