# Generated by Django 5.0.6 on 2026-05-01 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_rulecontrol_promotion_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecontrol',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Phase-9 parameter dict for parameter-aware rules. Empty for hand-coded rules.'),
        ),
        migrations.CreateModel(
            name='RuleMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_rule', models.CharField(db_index=True, help_text='The rule_name being mutated.', max_length=100)),
                ('forked_rule', models.CharField(blank=True, help_text="Name of the new rule created when applied. Format: '{parent}_evolved_v{N}'.", max_length=120)),
                ('parent_params', models.JSONField(default=dict)),
                ('mutated_params', models.JSONField(default=dict)),
                ('parameters_changed', models.JSONField(default=list, help_text='List of parameter names that differ from parent.')),
                ('parent_expectancy', models.FloatField(blank=True, null=True)),
                ('proposed_score', models.FloatField(blank=True, help_text='Heuristic score from the proposer (synthetic).', null=True)),
                ('score_method', models.CharField(default='heuristic', help_text='heuristic | walk_forward | manual_backtest', max_length=24)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied (forked into new rule)'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='proposed', max_length=12)),
                ('rationale', models.TextField(blank=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_mutations_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_at'],
                'indexes': [models.Index(fields=['state', '-proposed_at'], name='signals_rul_state_ccb361_idx'), models.Index(fields=['parent_rule', '-proposed_at'], name='signals_rul_parent__2aece5_idx')],
            },
        ),
    ]
