# Generated by Django 5.0.6 on 2026-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_rulecontrol_parameters_rulemutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulemutation',
            name='score_details',
            field=models.JSONField(blank=True, default=dict, help_text='Method-specific score breakdown (e.g. train/test expectancies for walk_forward).'),
        ),
        migrations.AlterField(
            model_name='rulemutation',
            name='proposed_score',
            field=models.FloatField(blank=True, help_text='Score from the proposer. Method-specific; see score_method + score_details.', null=True),
        ),
    ]
