# Generated by Django 5.0.6 on 2026-05-01 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_asset_class'),
        ('signals', '0011_rulemutation_score_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='bullish', max_length=10)),
                ('asset_classes', models.JSONField(default=list, help_text='List of asset_class strings the scanner will run on. Empty = all.')),
                ('conditions', models.JSONField(default=list, help_text='List of {kind, params, weight} dicts.')),
                ('min_match_score', models.FloatField(default=0.7, help_text='Composite score 0..1 that must be exceeded to create a flag.')),
                ('suggested_horizon_days', models.IntegerField(default=5, help_text="How many days to wait before resolving the flag's implied move.")),
                ('sizing', models.JSONField(blank=True, default=dict, help_text='Sizing config: {stop_atr_mult: 1.5, target_rr: 2.0} or {stop_pct: 2.0, target_pct: 4.0}.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_setups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default='bullish', max_length=10)),
                ('score', models.FloatField(help_text='Composite condition match score 0..1.')),
                ('conditions_evaluated', models.JSONField(default=list, help_text='Per-condition evaluator output: list of {kind, matched, score, details}.')),
                ('price_at_flag', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('suggested_entry', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('suggested_stop', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('suggested_target', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('horizon_days', models.IntegerField(default=5)),
                ('outcome', models.CharField(blank=True, choices=[('hit', 'Implied move played out'), ('miss', 'Implied move did not play out'), ('neutral', 'Move within neutral band'), ('expired', 'Resolution window passed')], max_length=10)),
                ('resolved_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_flags', to='instruments.instrument')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_flags', to='signals.signal')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='signals.opportunitysetup')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['-scanned_at'], name='signals_opp_scanned_3bde65_idx'), models.Index(fields=['setup', '-scanned_at'], name='signals_opp_setup_i_03fcae_idx'), models.Index(fields=['outcome', '-scanned_at'], name='signals_opp_outcome_d6b014_idx')],
            },
        ),
    ]
