# Generated by Django 5.0.6 on 2026-05-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_opportunitysetup_opportunityflag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveredSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(blank=True, max_length=20)),
                ('direction', models.CharField(default='bullish', max_length=10)),
                ('features', models.JSONField(default=list)),
                ('n_supporting_moves', models.IntegerField(default=0)),
                ('n_total_moves', models.IntegerField(default=0)),
                ('support', models.FloatField(default=0.0)),
                ('lift', models.FloatField(default=1.0)),
                ('hit_rate', models.FloatField(default=0.0)),
                ('lookback_days', models.IntegerField(default=730)),
                ('forward_horizon_days', models.IntegerField(default=5)),
                ('mined_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('activated', 'Activated'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='proposed', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('activated_setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_origins', to='signals.opportunitysetup')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_setups_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mined_at'],
                'indexes': [models.Index(fields=['state', '-mined_at'], name='signals_dis_state_06e633_idx'), models.Index(fields=['asset_class', 'direction'], name='signals_dis_asset_c_0fc29c_idx')],
            },
        ),
    ]
