# Generated by Django 5.0.6 on 2026-05-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_discoveredsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, help_text="e.g. 'price_tick', 'news', 'funding_rate'", max_length=40)),
                ('symbol', models.CharField(blank=True, db_index=True, help_text='Optional — extracted from payload for display.', max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('rules_evaluated', models.IntegerField(default=0)),
                ('rules_fired', models.IntegerField(default=0)),
                ('fired_rule_names', models.JSONField(default=list)),
                ('signal_ids', models.JSONField(default=list, help_text='IDs of Signal rows created from this event.')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatch_ms', models.FloatField(default=0, help_text='Wall-clock time spent in dispatch_event (ms).')),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['-received_at'], name='signals_fas_receive_73cfeb_idx'), models.Index(fields=['event_type', '-received_at'], name='signals_fas_event_t_ac8c08_idx')],
            },
        ),
    ]
