# Generated by Django 5.2.12 on 2026-08-25 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_positionreview'),
        ('signals', '0017_smcsignal_ict_setups'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleaction',
            name='source_brain_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_actions', to='brain.brainreport'),
        ),
    ]
