"""Write the IBKR Gateway logins from the database into .env.

Sauron never authenticates to IBKR — it connects to a socket that is
already logged in — so a username and password exist only so IBC can
sign the Gateway container in at BOOT. That is the whole reason this
command exists rather than a save button that "just works": a container
reads its environment once, and restarting a Gateway mid-session drops
a live broker connection, possibly with positions open. Applying a new
credential is therefore something an operator does deliberately, at a
moment they choose.

The database stays the source of truth: encrypted at rest, backed up
with everything else, editable by the account's owner. This renders it.

    python manage.py render_ibkr_env            # show what would change
    python manage.py render_ibkr_env --write    # write it

Then restart only the slot you changed:

    ./deploy/dc --profile ibkr2 up -d ibgateway-2
"""
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

BEGIN = "# >>> sauron: IBKR gateway logins (managed — edit in the UI)"
END = "# <<< sauron: IBKR gateway logins"


class Command(BaseCommand):
    help = "Render IBKR Gateway logins from the database into .env."

    def add_arguments(self, parser):
        parser.add_argument("--write", action="store_true",
                            help="Write .env instead of printing the block.")
        parser.add_argument("--env", default="",
                            help="Path to .env (default: repo root).")

    def handle(self, *args, **opts):
        from bot_program.models import IBKRAccount

        block = self._render(IBKRAccount)
        if not opts["write"]:
            self.stdout.write(block)
            self.stdout.write(self.style.WARNING(
                "\nNothing written. Re-run with --write, then restart the "
                "slots you changed."))
            return

        path = Path(opts["env"]) if opts["env"] else (
            Path(settings.BASE_DIR).parent / ".env")
        if not path.is_file():
            raise CommandError(
                f"No .env at {path}. Pass --env with its path — this command "
                f"will not create one, because a half-written .env is worse "
                f"than none.")

        text = path.read_text(encoding="utf-8")
        if BEGIN in text and END in text:
            head = text[:text.index(BEGIN)]
            tail = text[text.index(END) + len(END):].lstrip("\n")
            text = head + block + ("\n" + tail if tail else "\n")
        else:
            text = text.rstrip("\n") + "\n\n" + block
        path.write_text(text, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {path}"))
        self.stdout.write(
            "Restart only the slots you changed, e.g.\n"
            "  ./deploy/dc --profile ibkr up -d ibgateway\n"
            "A restart drops that Gateway's session — check for open "
            "positions first.")

    def _render(self, model) -> str:
        lines = [BEGIN,
                 "# Generated by `manage.py render_ibkr_env`. The database is",
                 "# the source of truth; edits here are overwritten.",
                 ""]
        seen = {}
        for acct in model.objects.all().order_by("gateway_slot", "id"):
            user, pw = acct.get_login()
            if not (user and pw):
                continue
            slot = int(acct.gateway_slot or 1)
            if slot in seen and seen[slot] != user:
                # Two DIFFERENT logins on one slot is the mistake this
                # whole layout exists to prevent: one Gateway session is
                # one username, so the second would silently never
                # connect. Named, not merged.
                self.stderr.write(self.style.ERROR(
                    f"slot {slot} has two different logins "
                    f"({seen[slot]} and {user}) — give one of them its own "
                    f"slot, or they will fight over the same container"))
                continue
            seen[slot] = user
            p = acct.env_prefix
            # The port decides, and the socat relay ports carry the
            # same split: 4003 fronts the live 4001, 4004 the paper
            # 4002. Deriving 4003 as "paper" would relaunch a LIVE
            # login in paper mode - the wrong direction to fail.
            mode = ("live" if acct.port in model.LIVE_PORTS
                    else "paper")
            lines += [f"{p}_USERNAME={user}",
                      f"{p}_PASSWORD={pw}",
                      f"{p}_TRADING_MODE={mode}",
                      ""]
        if not seen:
            lines.append("# No IBKR logins stored yet — add one in the UI.")
            lines.append("")
        lines.append(END)
        return "\n".join(lines)
